#include "NOISE_CANCEL.h"

//THIS FUNCTION IS USED TO FIND THE MAXIMUM VAUE IN THE MAGNITUDE SPECTRUM AND ELIMINATE ALL THE NOISES 
void OMIT_NOISE(){   

 float STORE = 0;
 for(uint16_t i=0; i<NUMBER_OF_SAMPLES; i++){
    if(MAGNITUDE_SAMPLES[i].MAGNITUDE > STORE){
         STORE = MAGNITUDE_SAMPLES[i].MAGNITUDE ;
    }
 }
 STORE = STORE * 0.1;  //TAKE 10% OF IT  
 uint16_t TEMPORARY_SAMPLES = (NUMBER_OF_SAMPLES - 1) * 2;
 for(uint16_t i=0; i<NUMBER_OF_SAMPLES; i++){
    if(MAGNITUDE_SAMPLES[i].MAGNITUDE < STORE){
        MAGNITUDE_SAMPLES[i].MAGNITUDE = 0;
        if(i == 0){
            FFT_SAMPLES[i].REAL_VALUE = 0;
            FFT_SAMPLES[i].IMAGINARY_VALUE = 0;
        }else{
            FFT_SAMPLES[i].REAL_VALUE = 0;
            FFT_SAMPLES[i].IMAGINARY_VALUE = 0;
            FFT_SAMPLES[TEMPORARY_SAMPLES - 1].REAL_VALUE = 0;
            FFT_SAMPLES[TEMPORARY_SAMPLES - 1].IMAGINARY_VALUE = 0;
        }
    }
 }  
 MATLAB_FUNCTION("FREQUENCY", 3);
MAGNITUDE_SPECTRUM();

}